apiVersion: v1
kind: Service
metadata:
  name: pet-clinic-web-service
spec:
  selector:
    app: pet-clinic-web
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: debug
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
