apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-root-password
  namespace: default
spec:
  encryptedData:
    password: AgAhn8r63f/o5AbAUKdDChQ52RrV1awOlpvN9KEQ/qrriFSJChkI2lG9RrtxfGV903gPoZtigUkfZLq5SSNs/7bj3mZIMQSd+Z7dPbp8hFetXRRfQPhknw4906B9YtjwsvAshMWXow5CvlWLKx7QunyYqnnTxvmWzhsGUYpqKEx+VLc996zqbesGYciKfC07rPDQxy3XbSJO2lJEAkM52i1fOJRHHjjxBcwY9qEQl2DKFxM7vtpRyJzjv2vdezUWDDPqscIqNkmwDJax3F8RzuaZ7GKHMmTM6QxrsRdpG4hBt+XTdVJ8j201d+QMSLiQzX8IY50zBEziQM4f1Dv8qmBUEXXYaCFlPGv+RZfr1NSLVX0BWU63ec6eCxNstrzsNeIENJ17PqWM4nmbzWfMku02xhgu5As8U19GQK4D040f+YjNHeTe5A7UNEz3999JDKxWV64Kf/y50u8hWFspJkbveyxBopT9G7rQq5cUhDEqkE8Cq3vf4roJT3jorTxaDog9o5f07wu9z18XKiZ7flHkb9k7EiZrb1gT2c0Q6LBI+SzIhoCLE91Hh4AI5AEoCM1zOo01UbhjWM3XWrP+djn9WGiHJqjgH0b889MGq/Wzd5Dlv35JQnedTGXO+kDZGtn9aZhMcoRXJj9dNZ3ZQliCQSWPKmfjyVJoXNC/xiT3yHmzGyYOP8ZEpskgzGc06vVWGij2PPAa8A==
  template:
    metadata:
      creationTimestamp: null
      name: mysql-root-password
      namespace: default
