apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-user-password
  namespace: default
spec:
  encryptedData:
    password: AgAjD+lqIVztev1YFL9Zi6LHrahF5Sq/7Gk7DyHjEVBR35E4V2SHmfSy5s4B+ZKSkOFFWP+Pf0ob+tnVNVSs5XT33EYx0PRSAmSzXZsIYDQNce6nqVvr3bCnCVJdZ6Cib5UG5oH2MVD1ln7SCYEBwoUSpKsPN/m+YJ5dwh0b+8Bnh29qgmsJmWLSxVG1uVfoEcP8bMMhj3Wrk5u5iMuHm7u8qE53UpJOAv4r46lFlPJTBokpmkYSIX0wzcPiT9fjtz/S0xmveUs2f0aGxDIlgqTiskZ536MDlRUdF2dGHoM0DKSoVaTW6D1HjK0ON2MpIjFrJCvDahZcw+Vj3Ke4Zf5IvgPKEu99Zuau+qMdNc9rUxKEZ+OB+5/+RYgY7YrGN2vGvolWAWuxk082zJCLPHSqiiQWm+dw21UA/pE8FE0g8Ptfsl0K4kruMy9ehPjhIjHNQrhghSaGTxBZxPrcqwVPC3FfPeVj0gUY84gXJ0/D6lLQVxXY/EPr11U4CaagYxNk4PnF487V1hfp8GiI0AI/8BgLaY4VrgAnG+CFzTOWmIQcvtpXxscKp648psGPYkN0KU6s3NJUyxUZUIMyFAItcy50DR5CQKXCxwgimgZI/LS/sEZQCyJOD/s43j7xImahxwl3XS9iNjYIXzeyrZlTjFuXJfHUT7RJV4vMhlAz7H1aeMjN8RuyHE/PTdmGYZpyV2jpjA==
  template:
    metadata:
      creationTimestamp: null
      name: mysql-user-password
      namespace: default

